In [323]:
iris = [ [ 5.1, 1.3, 1.2, 3.3 ], [ 5.2, 1.2, 1.1, 3.2 ] ]


In [324]:
[ 1, 2.3, "stringa", None, False ]

[1, 2.3, 'stringa', None, False]

In [325]:
import numpy as np

In [336]:
x = np.array([ 1000, 2, 3 ], dtype=np.int8)

/var/folders/6x/r6kfn_352c747w5tt44hrxhm0000gn/T/ipykernel_9560/1245939900.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 1000 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  x = np.array([ 1000, 2, 3 ], dtype=np.int8)


In [337]:
x.dtype

dtype('int8')

In [338]:
x

array([-24,   2,   3], dtype=int8)

In [345]:
np.zeros((150, 4, 16))

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [343]:
matrice = []
for i in range(150):
    riga = []
    for j in range(4):
        riga.append(0)
    matrice.append(riga)

In [344]:
matrice

[[0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0,

In [346]:
np.ones((150, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],


In [348]:
np.full((3, 2), 0)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [349]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [350]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [351]:
np.zeros((5, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [352]:
list(range(0, 22))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [354]:
list(range(0, 20, 2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [355]:
list(range(0, 20, 0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [357]:
np.arange(0, 20, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [358]:
np.linspace(0, 20, 15)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

In [361]:
np.random.random((3, 2))

array([[0.52152566, 0.54461618],
       [0.40033586, 0.09552429],
       [0.10388767, 0.74935003]])

In [364]:
x = np.random.normal(3, 0.2, (4,3))

In [365]:
x

array([[3.56181207, 2.74849838, 2.81920793],
       [2.9615936 , 2.76555532, 3.26656281],
       [2.97998441, 2.74205286, 3.05316119],
       [3.32062576, 3.07721903, 2.86400137]])

In [366]:
x.ndim

2

In [367]:
x.shape

(4, 3)

In [368]:
x.shape[0]

4

In [369]:
x.size

12

In [370]:
x = np.array([ -1, 3, 2, -5, 4 ])

In [371]:
x

array([-1,  3,  2, -5,  4])

In [372]:
np.abs(x)

array([1, 3, 2, 5, 4])

In [373]:
x = np.array([[3, -2], [-5, 4]])

In [374]:
x

array([[ 3, -2],
       [-5,  4]])

In [376]:
np.abs(x)

array([[3, 2],
       [5, 4]])

In [384]:
x = np.random.random((3, 2))

In [385]:
x

array([[0.83676635, 0.02697649],
       [0.23718615, 0.22689641],
       [0.10108121, 0.46179694]])

In [386]:
y = np.random.random((3,2))

In [387]:
y

array([[0.8264915 , 0.94976752],
       [0.37971633, 0.88433041],
       [0.41096319, 0.23092252]])

In [388]:
x + y

array([[1.66325785, 0.97674401],
       [0.61690248, 1.11122682],
       [0.5120444 , 0.69271946]])

In [390]:
x.min()


0.0269764919304738

In [391]:
x.max()

0.8367663499225229

In [392]:
np.min(x), np.max(x)

(0.0269764919304738, 0.8367663499225229)

In [393]:
x.sum()

1.890703553109919

In [395]:
x.var()

0.07272090192026374

In [402]:
x = np.random.random(10)

In [403]:
x

array([0.01280064, 0.54161768, 0.87276935, 0.30851979, 0.89795553,
       0.78622032, 0.66274908, 0.66808108, 0.92160119, 0.43568326])

In [404]:
x.max()

0.9216011857791415

In [405]:
x.argmax()

8

In [407]:
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)

In [409]:
X.shape

(150, 4)

In [413]:
X.mean()

3.4644999999999997

In [416]:
A = np.random.random((3,2))

In [417]:
A

array([[0.2658372 , 0.16034708],
       [0.77387343, 0.75203582],
       [0.8264293 , 0.4804762 ]])

In [419]:
A.sum(axis=0)

array([1.86613994, 1.3928591 ])

In [420]:
A.sum(axis=1)

array([0.42618428, 1.52590926, 1.3069055 ])

In [423]:
from time import time

a = time()
for i in range(1000):
    X.mean(axis=0)
b = time()

print(b-a)

0.014973878860473633


In [424]:
X.mean(axis=0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [426]:
X.var(axis=0)

array([0.68112222, 0.18871289, 3.09550267, 0.57713289])

In [428]:
X.std(axis=0) ** 2

array([0.68112222, 0.18871289, 3.09550267, 0.57713289])

In [430]:
y = np.random.random(20)

In [431]:
y

array([0.85037299, 0.92164715, 0.47143506, 0.11492902, 0.87423193,
       0.84378224, 0.72993285, 0.15723942, 0.29434596, 0.98572525,
       0.77158294, 0.86504344, 0.08948838, 0.00627802, 0.49707036,
       0.19928597, 0.81245605, 0.72897006, 0.62398961, 0.07279744])

In [432]:
np.sort(y)

array([0.00627802, 0.07279744, 0.08948838, 0.11492902, 0.15723942,
       0.19928597, 0.29434596, 0.47143506, 0.49707036, 0.62398961,
       0.72897006, 0.72993285, 0.77158294, 0.81245605, 0.84378224,
       0.85037299, 0.86504344, 0.87423193, 0.92164715, 0.98572525])

In [438]:
x = np.random.random((3, 5))

In [439]:
x

array([[0.26000381, 0.69307932, 0.32312342, 0.93803959, 0.51190703],
       [0.20769915, 0.26217488, 0.88016897, 0.3072722 , 0.68094017],
       [0.78373176, 0.86963244, 0.19822844, 0.19574327, 0.99913411]])

In [441]:
np.sort(x, axis=1)

array([[0.26000381, 0.32312342, 0.51190703, 0.69307932, 0.93803959],
       [0.20769915, 0.26217488, 0.3072722 , 0.68094017, 0.88016897],
       [0.19574327, 0.19822844, 0.78373176, 0.86963244, 0.99913411]])

In [442]:
np.sort(x, axis=0)

array([[0.20769915, 0.26217488, 0.19822844, 0.19574327, 0.51190703],
       [0.26000381, 0.69307932, 0.32312342, 0.3072722 , 0.68094017],
       [0.78373176, 0.86963244, 0.88016897, 0.93803959, 0.99913411]])

In [443]:
A = np.array([[1,1],[2,2]])
B = np.array([[2,2],[1,1]])

In [444]:
A


array([[1, 1],
       [2, 2]])

In [445]:
B

array([[2, 2],
       [1, 1]])

In [446]:
A * B

array([[2, 2],
       [2, 2]])

In [448]:
np.dot(B, A)

array([[6, 6],
       [3, 3]])

In [450]:
x = np.array([1,2,3])
y = np.array([[11],[12],[13]])
print(x)
print(y)

[1 2 3]
[[11]
 [12]
 [13]]


In [451]:
x + y

array([[12, 13, 14],
       [13, 14, 15],
       [14, 15, 16]])

In [452]:
x.shape

(3,)

In [453]:
y.shape

(3, 1)

In [455]:
X.shape

(150, 4)

In [456]:
X.mean(axis=0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [458]:
X2 = (X - X.mean(axis=0))

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [465]:
X3 = X2 / X.std(axis=0)

In [466]:
X3.mean(axis=0)

array([-1.69031455e-15, -1.84297022e-15, -1.69864123e-15, -1.40924309e-15])

In [467]:
X3.var(axis=0)

array([1., 1., 1., 1.])

In [468]:
X3.shape

(150, 4)

In [476]:
l = [ [ 'a', 'b', 'c' ], [1,2,3] ]

In [477]:
l[1]

[1, 2, 3]

In [478]:
l[1][2]

3

In [487]:
x = np.random.random((5, 3))

In [488]:
x

array([[0.2818567 , 0.11893986, 0.72588269],
       [0.72879682, 0.46478838, 0.96850479],
       [0.89723237, 0.07813022, 0.87793931],
       [0.56414223, 0.84783823, 0.86172363],
       [0.66118904, 0.81044459, 0.82413888]])

In [489]:
x[3,2]

0.8617236335938492

In [490]:
x

array([[0.2818567 , 0.11893986, 0.72588269],
       [0.72879682, 0.46478838, 0.96850479],
       [0.89723237, 0.07813022, 0.87793931],
       [0.56414223, 0.84783823, 0.86172363],
       [0.66118904, 0.81044459, 0.82413888]])

In [493]:
x[0:3, 0:2]

array([[0.2818567 , 0.11893986],
       [0.72879682, 0.46478838],
       [0.89723237, 0.07813022]])

In [498]:
x[::-1, :2]

array([[0.66118904, 0.81044459],
       [0.56414223, 0.84783823],
       [0.89723237, 0.07813022],
       [0.72879682, 0.46478838],
       [0.2818567 , 0.11893986]])

In [501]:
x = np.random.random(5)


In [502]:
x

array([0.38282792, 0.70270883, 0.71040017, 0.85885565, 0.6891513 ])

In [503]:
mask = np.array([ True, True, False, False, True ])

In [504]:
x[mask]

array([0.38282792, 0.70270883, 0.6891513 ])

In [505]:
x

array([0.38282792, 0.70270883, 0.71040017, 0.85885565, 0.6891513 ])

In [510]:
x[x > 0.5]

array([0.70270883, 0.71040017, 0.85885565, 0.6891513 ])

In [514]:
x = np.random.random((5, 3))

In [520]:
x

array([[0.64808447, 0.69732721, 0.52993382],
       [0.65827824, 0.02293328, 0.28285703],
       [0.41486457, 0.35645668, 0.91767889],
       [0.8195057 , 0.20430002, 0.5872671 ],
       [0.4267325 , 0.83855199, 0.54919346]])

In [518]:
x[x > 0.5]

array([0.64808447, 0.69732721, 0.52993382, 0.65827824, 0.91767889,
       0.8195057 , 0.5872671 , 0.83855199, 0.54919346])

In [521]:
x[x > 0.5] = 1000

In [522]:
x

array([[1.00000000e+03, 1.00000000e+03, 1.00000000e+03],
       [1.00000000e+03, 2.29332808e-02, 2.82857029e-01],
       [4.14864570e-01, 3.56456676e-01, 1.00000000e+03],
       [1.00000000e+03, 2.04300021e-01, 1.00000000e+03],
       [4.26732503e-01, 1.00000000e+03, 1.00000000e+03]])

In [523]:
x = np.random.random(50)

In [524]:
x

array([0.29399258, 0.55682559, 0.6207513 , 0.80668094, 0.00883231,
       0.20886306, 0.00847635, 0.67136131, 0.02431324, 0.72279737,
       0.36496252, 0.38294131, 0.33685194, 0.18578321, 0.49059336,
       0.97459567, 0.59204164, 0.19736329, 0.30891558, 0.18127179,
       0.24294705, 0.75549176, 0.69290509, 0.78373218, 0.83311892,
       0.01538335, 0.77852723, 0.04317569, 0.55286931, 0.43674812,
       0.70656422, 0.34425581, 0.54475665, 0.69696209, 0.24890545,
       0.91592656, 0.72104624, 0.83795157, 0.23464406, 0.98960845,
       0.72063132, 0.69673523, 0.3547686 , 0.12682097, 0.37478288,
       0.96584092, 0.42686965, 0.59216532, 0.49829665, 0.18175263])

In [526]:
"""
& => AND
| => OR
~ => NOT
"""

array([0.55682559, 0.6207513 , 0.80668094, 0.67136131, 0.72279737,
       0.36496252, 0.38294131, 0.33685194, 0.49059336, 0.97459567,
       0.59204164, 0.30891558, 0.75549176, 0.69290509, 0.78373218,
       0.83311892, 0.77852723, 0.55286931, 0.43674812, 0.70656422,
       0.34425581, 0.54475665, 0.69696209, 0.91592656, 0.72104624,
       0.83795157, 0.98960845, 0.72063132, 0.69673523, 0.3547686 ,
       0.37478288, 0.96584092, 0.42686965, 0.59216532, 0.49829665])

In [528]:
x[(x > 0.3)&(x < 0.7)]

array([0.55682559, 0.6207513 , 0.67136131, 0.36496252, 0.38294131,
       0.33685194, 0.49059336, 0.59204164, 0.30891558, 0.69290509,
       0.55286931, 0.43674812, 0.34425581, 0.54475665, 0.69696209,
       0.69673523, 0.3547686 , 0.37478288, 0.42686965, 0.59216532,
       0.49829665])

In [529]:
x[(x > 0.3)|(x < 0.7)]

array([0.29399258, 0.55682559, 0.6207513 , 0.80668094, 0.00883231,
       0.20886306, 0.00847635, 0.67136131, 0.02431324, 0.72279737,
       0.36496252, 0.38294131, 0.33685194, 0.18578321, 0.49059336,
       0.97459567, 0.59204164, 0.19736329, 0.30891558, 0.18127179,
       0.24294705, 0.75549176, 0.69290509, 0.78373218, 0.83311892,
       0.01538335, 0.77852723, 0.04317569, 0.55286931, 0.43674812,
       0.70656422, 0.34425581, 0.54475665, 0.69696209, 0.24890545,
       0.91592656, 0.72104624, 0.83795157, 0.23464406, 0.98960845,
       0.72063132, 0.69673523, 0.3547686 , 0.12682097, 0.37478288,
       0.96584092, 0.42686965, 0.59216532, 0.49829665, 0.18175263])

In [532]:
y

array([[11],
       [12],
       [13]])

In [533]:
X, y = load_iris(return_X_y=True)

In [534]:
X.shape

(150, 4)

In [536]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [539]:
X[y == 0].mean(axis=0)

array([5.006, 3.428, 1.462, 0.246])

In [540]:
X[y == 1].mean(axis=0)

array([5.936, 2.77 , 4.26 , 1.326])

In [541]:
X[y == 2].mean(axis=0)

array([6.588, 2.974, 5.552, 2.026])

In [542]:
X[y == 0].std(axis=0), X[y == 1].std(axis=0), X[y == 2].std(axis=0)

(array([0.34894699, 0.37525458, 0.17191859, 0.10432641]),
 array([0.51098337, 0.31064449, 0.46518813, 0.19576517]),
 array([0.62948868, 0.31925538, 0.54634787, 0.27188968]))

In [545]:
import json

f = open("/Users/fgiobergia/Downloads/to-bike.json")
obj = json.load(f)

In [547]:
type(obj)

dict

In [552]:
obj["network"].keys()

dict_keys(['company', 'href', 'id', 'location', 'name', 'source', 'stations'])

In [563]:
count = 0
for station in obj["network"]["stations"]:
    if station["extra"]["status"] == "online":
        count += 1
print("online", count)

online 1


In [565]:
len([ s for s in obj["network"]["stations"] if s["extra"]["status"] == "online" ])

1

In [567]:
count_bikes = 0
count_slots = 0
for station in obj["network"]["stations"]:
    count_bikes += station["free_bikes"]
    count_slots += station["empty_slots"]
print(count_bikes, "bikes")
print(count_slots, "slots")

95 bikes
62 slots


In [569]:
sum(list(map(lambda station: station["free_bikes"], obj["network"]["stations"])))

95

In [570]:
sum(list(map(lambda station: station["empty_slots"], obj["network"]["stations"])))

62

In [571]:
sum([ station["free_bikes"] for station in obj["network"]["stations"] ])

95

In [572]:
sum([ station["empty_slots"] for station in obj["network"]["stations"] ])

62