In [1]:
import pandas as pd

In [20]:
import numpy as np

s = pd.Series([22, 24, 23, 18], index=['giorno 1', 'giorno 2', 'giorno 3', 'giorno 4'])

In [4]:
print(s)

giorno 1    22
giorno 2    24
giorno 3    23
giorno 4    18
dtype: int64


In [5]:
pd.Series([22, 24, 23, 18])

0    22
1    24
2    23
3    18
dtype: int64

In [14]:
s = pd.Series({'giorno 12': 22, 'giorno 13': 24, 'giorno 14': 23, 'giorno 15': 18})

In [8]:
s.index

Index(['giorno 1', 'giorno 2', 'giorno 3', 'giorno 4'], dtype='object')

In [10]:
type(s.values)

numpy.ndarray

In [11]:
s.values

array([22, 24, 23, 18])

In [12]:
s.loc['giorno 1']

22

In [18]:
s.iloc[0]

22

In [21]:
s.loc["giorno 1":"giorno 3"]

giorno 1    22
giorno 2    24
giorno 3    23
dtype: int64

In [22]:
s

giorno 1    22
giorno 2    24
giorno 3    23
giorno 4    18
dtype: int64

In [27]:
index = [ f"giorno {i}" for i in range(1, 61) ]
s = pd.Series(np.random.uniform(10, 30, size=60), index=index)

In [34]:
mask = (s < 11) | (s > 29)

In [35]:
s[mask]

giorno 14    29.070589
giorno 24    10.233852
giorno 40    29.897407
giorno 48    29.292396
giorno 54    10.125018
giorno 56    29.621302
dtype: float64

In [36]:
s_a = pd.Series([20, 22, 23, 24], index=[f"giorno {i}" for i in range(1, 5)])
s_b = pd.Series([21, 22, 22, 26], index=[f"giorno {i}" for i in range(1, 5)])
s_c = pd.Series([18, 19, 20, 20], index=[f"giorno {i}" for i in range(1, 5)])

In [43]:
{ "Sensore A": s_a, "Sensore B": s_b, "Sensore C": s_c }

{'Sensore A': giorno 1    20
 giorno 2    22
 giorno 3    23
 giorno 4    24
 dtype: int64,
 'Sensore B': giorno 1    21
 giorno 2    22
 giorno 3    22
 giorno 4    26
 dtype: int64,
 'Sensore C': giorno 1    18
 giorno 2    19
 giorno 3    20
 giorno 4    20
 dtype: int64}

In [41]:
pd.DataFrame({ "Sensore A": s_a, "Sensore B": s_b, "Sensore C": s_c })

Sensore A  Sensore B  Sensore C
giorno 1         20         21         18
giorno 2         22         22         19
giorno 3         23         22         20
giorno 4         24         26         20

In [44]:
d = { "Sensore A": [20, 22, 23, 24],
      "Sensore B": [21, 22, 22, 26],
      "Sensore C": [18, 19, 20, 20] }

In [47]:
pd.DataFrame(d, index=["giorno 1", "giorno 2", 'giorno 3', 'giorno 4'])

Sensore A  Sensore B  Sensore C
Giorno 1         20         21         18
giorno 2         22         22         19
giorno 3         23         22         20
giorno 4         24         26         20

In [48]:
m = np.random.uniform(10, 30, size=(4, 3))

In [52]:
pd.DataFrame(m, index=[f'giorno {i}' for i in range(1,5)], columns=[f"Sensore {x}" for x in "ABC"])

Sensore A  Sensore B  Sensore C
giorno 1  12.838051  21.062894  27.454451
giorno 2  28.137449  24.414432  12.515111
giorno 3  14.503287  28.446719  29.051100
giorno 4  23.631966  19.938175  22.783830

In [62]:
df = pd.read_csv("dataset.csv", sep=";", keep_default_na=False)

In [63]:
df

altezza larghezza spessore
0        0        NA        2
1        3         4       NA
2        6        NA        8
3        9        10       11

In [64]:
df.to_csv("file.csv", sep="?")

In [66]:
price = pd.Series([1.0, 1.4, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, 8], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])
df = pd.DataFrame({'Price':price, 'Quantity':quantity,
                   'Liters':liters})
df

Price  Quantity  Liters
a    1.0         5     1.5
b    1.4        10     0.3
c    5.0         8     1.0

In [67]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [68]:
df.columns

Index(['Price', 'Quantity', 'Liters'], dtype='object')

In [69]:
df.values

array([[ 1. ,  5. ,  1.5],
       [ 1.4, 10. ,  0.3],
       [ 5. ,  8. ,  1. ]])

In [70]:
df

Price  Quantity  Liters
a    1.0         5     1.5
b    1.4        10     0.3
c    5.0         8     1.0

In [76]:
df.loc["b":"c", "Price":"Quantity"]

Price  Quantity
b    1.4        10
c    5.0         8

In [81]:
mask = df["Price"] > 2

In [82]:
mask

a    False
b    False
c     True
Name: Price, dtype: bool

In [83]:
df[mask]

Price  Quantity  Liters
c    5.0         8     1.0

In [84]:
df["Price"] = 0

In [85]:
df.

Price  Quantity  Liters
a      0         5     1.5
b      0        10     0.3
c      0         8     1.0

In [86]:
df.loc["a", "Quantity"] = df.loc["a", "Quantity"] + 10

In [88]:
df["Color"] = ["Blue", "Verde", "Bianco"]

In [89]:
df

Price  Quantity  Liters   Color
a      0        15     1.5    Blue
b      0        10     0.3   Verde
c      0         8     1.0  Bianco

In [92]:
df.drop(columns=["Price"], inplace=True)

In [96]:
df

Quantity  Liters   Color
a        15     1.5    Blue
b        10     0.3   Verde
c         8     1.0  Bianco

In [99]:
df.rename(columns={ "Color": "Colour" }, inplace=True)

In [101]:
df

Quantity  Liters  Colour
a        15     1.5    Blue
b        10     0.3   Verde
c         8     1.0  Bianco

In [102]:
df.drop

Quantity  Liters  Colour
a        15     1.5    Blue
b        10     0.3   Verde
c         8     1.0  Bianco

In [103]:
price = pd.Series([1.0, 1.4, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, 8], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])
df = pd.DataFrame({'Price':price, 'Quantity':quantity,
                   'Liters':liters})
df

Price  Quantity  Liters
a    1.0         5     1.5
b    1.4        10     0.3
c    5.0         8     1.0

In [106]:
np.exp(df)

Price      Quantity    Liters
a    2.718282    148.413159  4.481689
b    4.055200  22026.465795  1.349859
c  148.413159   2980.957987  2.718282

In [109]:
np.random.random((5, 3)) + np.random.random((5, 3))

array([[1.31594691, 1.26600665, 0.63480682],
       [0.6388095 , 0.99573905, 0.46555023],
       [1.32200206, 1.15901329, 0.92387522],
       [1.08212339, 0.58804895, 1.0818892 ],
       [0.55227675, 0.73991586, 1.0315979 ]])

In [110]:
df

Price  Quantity  Liters
a    1.0         5     1.5
b    1.4        10     0.3
c    5.0         8     1.0

In [111]:
df2 = pd.DataFrame(np.random.random((3,3)))

In [112]:
df

Price  Quantity  Liters
a    1.0         5     1.5
b    1.4        10     0.3
c    5.0         8     1.0

In [113]:
df2

0         1         2
0  0.841411  0.806530  0.659529
1  0.608687  0.697052  0.976846
2  0.169486  0.476842  0.215007

In [123]:
s1 = pd.Series([1,2,3], index=["giorno 1","giorno 2", "giorno 3"])
s2 = pd.Series([4,5,6], index=["giorno 1","giorno 2", "giorno 5"])

In [124]:
s1

giorno 1    1
giorno 2    2
giorno 3    3
dtype: int64

In [125]:

s2

giorno 1    4
giorno 2    5
giorno 5    6
dtype: int64

In [126]:
s1 + s2

giorno 1    5.0
giorno 2    7.0
giorno 3    NaN
giorno 5    NaN
dtype: float64

In [127]:
price = pd.Series([1.0, 1.4, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, 8], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])
df = pd.DataFrame({'Price':price, 'Quantity':quantity,
                   'Liters':liters})
df

Price  Quantity  Liters
a    1.0         5     1.5
b    1.4        10     0.3
c    5.0         8     1.0

In [131]:
price = pd.Series([1.0, 1.4, 5], index=['a', 'b', 'c'])
quantity = pd.Series([15, 100, 80], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])
df2 = pd.DataFrame({'Price':price, 'nItems':quantity,
                   '[L]':liters})
df2

Price  nItems  [L]
a    1.0      15  1.5
b    1.4     100  0.3
c    5.0      80  1.0

In [132]:
df + df2

Liters  Price  Quantity  [L]  nItems
a     NaN    2.0       NaN  NaN     NaN
b     NaN    2.8       NaN  NaN     NaN
c     NaN   10.0       NaN  NaN     NaN

In [138]:
s.min()

10.125017954627733

In [140]:
df.mean()

Price       2.466667
Quantity    7.666667
Liters      0.933333
dtype: float64

In [142]:
df.mean()

Price       2.466667
Quantity    7.666667
Liters      0.933333
dtype: float64

In [144]:
(df - df.mean()) / df.std()

Price  Quantity    Liters
a -0.665750 -1.059626  0.940102
b -0.484182  0.927173 -1.050702
c  1.149932  0.132453  0.110600

In [149]:
df.mean()

Price       2.466667
Quantity    7.666667
Liters      0.933333
dtype: float64

In [156]:
df.loc['a', 'Quantity':'Liters'] = np.nan

In [157]:
df

Price  Quantity  Liters
a    1.0       NaN     NaN
b    1.4      10.0     0.3
c    5.0       8.0     1.0

In [159]:
df.isnull()

Price  Quantity  Liters
a  False      True    True
b  False     False   False
c  False     False   False

In [165]:
df.isnull().mean(axis=1)

a    0.666667
b    0.000000
c    0.000000
dtype: float64

In [166]:
df.notnull()

Price  Quantity  Liters
a   True     False   False
b   True      True    True
c   True      True    True

In [167]:
~df.isnull()

Price  Quantity  Liters
a   True     False   False
b   True      True    True
c   True      True    True

In [169]:
s = pd.Series([None, 3, None, 4])

In [171]:
s.dropna()

1    3.0
3    4.0
dtype: float64

In [173]:
df.dropna()

Price  Quantity  Liters
b    1.4      10.0     0.3
c    5.0       8.0     1.0

In [198]:
df

Price  Quantity  Liters
a    1.0       NaN     NaN
b    NaN       NaN     NaN
c    5.0       8.0     1.0

In [204]:
df.fillna(method='bfill')

Price  Quantity  Liters
a    1.0       8.0     1.0
b    5.0       8.0     1.0
c    5.0       8.0     1.0

In [205]:
s1 = pd.Series([1,2,3,4])
s2 = pd.Series([4,8,12,16])

In [207]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [209]:
s2

0     4
1     8
2    12
3    16
dtype: int64

In [210]:
s3 = pd.concat((s1, s2))

In [211]:
s3

0     1
1     2
2     3
3     4
0     4
1     8
2    12
3    16
dtype: int64

In [212]:
s3.loc[0]

0    1
0    4
dtype: int64

In [215]:
s3.reset_index(drop=True)

0     1
1     2
2     3
3     4
4     4
5     8
6    12
7    16
dtype: int64

In [216]:
s3.reset_index()

index   0
0      0   1
1      1   2
2      2   3
3      3   4
4      0   4
5      1   8
6      2  12
7      3  16

In [217]:
pd.concat((s1, s2), ignore_index=True)

0     1
1     2
2     3
3     4
4     4
5     8
6    12
7    16
dtype: int64

In [221]:
price = pd.Series([1.0, 1.4, 5], index=['a', 'b', 'c'])
quantity = pd.Series([5, 10, 8], index=['a', 'b', 'c'])
liters = pd.Series([1.5, 0.3, 1], index=['a', 'b', 'c'])
df_prezzo_quantita_litri = pd.DataFrame({'Price':price, 'Quantity':quantity,
                   'Liters':liters})
df_prezzo_quantita_litri

Price  Quantity  Liters
a    1.0         5     1.5
b    1.4        10     0.3
c    5.0         8     1.0

In [222]:
df_colore_peso = pd.DataFrame({
    "Peso": [ 1.55, 0.4, 1.1 ],
    "Colore": ["blu", "verde", "bianco"]
}, index=['a','b','c'])

In [224]:
df_prezzo_quantita_litri

Price  Quantity  Liters
a    1.0         5     1.5
b    1.4        10     0.3
c    5.0         8     1.0

In [225]:
df_colore_peso

Peso  Colore
a  1.55     blu
b  0.40   verde
c  1.10  bianco

In [227]:
df_prezzo_quantita_litri.merge(df_colore_peso, right_index=True, left_index=True)

Price  Quantity  Liters  Peso  Colore
a    1.0         5     1.5  1.55     blu
b    1.4        10     0.3  0.40   verde
c    5.0         8     1.0  1.10  bianco

In [232]:
df = pd.DataFrame(np.random.randint(0, 10, size=(50, 4)), columns=[f'col {i}' for i in range(1,5)])

In [235]:
gb = df.groupby('col 1')

In [236]:
gb

In [238]:
for chiave, subset in gb:
    print(chiave, "=>" , len(subset))

0 => 5
1 => 4
2 => 5
3 => 5
4 => 7
5 => 1
6 => 8
7 => 4
8 => 6
9 => 5


In [242]:
df[df['col 1'] == 4].mean()

col 1    4.000000
col 2    2.857143
col 3    4.857143
col 4    4.714286
dtype: float64

In [247]:
gb.size()

col 1
0    5
1    4
2    5
3    5
4    7
5    1
6    8
7    4
8    6
9    5
dtype: int64

In [250]:
gb['col 2'].max()

col 1
0    8
1    8
2    9
3    9
4    7
5    8
6    8
7    9
8    9
9    4
Name: col 2, dtype: int64

In [256]:
df.groupby('col 1').filter(lambda g : len(g) > 6)

col 1  col 2  col 3  col 4
1       6      4      2      2
3       4      4      3      5
4       6      7      0      8
16      4      7      2      8
21      6      6      1      0
28      6      6      9      0
29      4      1      0      5
36      6      1      4      3
38      4      6      9      0
42      4      0      9      3
43      4      0      7      5
44      6      7      9      2
45      6      8      6      0
46      6      8      9      3
47      4      2      4      7